### ISSUE TITLE
Only last error is written to in case of multiple files

### ISSUE THREAD

**Issue by yogeshlonkar** [mila-labs/jshint-checkstyle-file-reporter#3]
On using reporter for multiple files  jshint only the error of last file is written to report.

**Comment by jrbostic** [comment]
PR #4 has a correction for this.  Would still require cleaning of the folder after running a lint, as there's no built in cleanup of the checkstyle files.  But since it's for Jenkins, it should just be added to .gitignore and cleanup can be worked into local build script.  I may continue to maintain or improve as needed.
